import { redirect } from "@remix-run/node";
import { Form, useLoaderData } from "@remix-run/react";
import { login } from "../../shopify.server";
import styles from "./styles.module.css";

export const loader = async ({ request }) => {
  const url = new URL(request.url);

  if (url.searchParams.get("shop")) {
    throw redirect(`/app?${url.searchParams.toString()}`);
  }

  return { showForm: Boolean(login) };
};

export default function App() {
  const { showForm } = useLoaderData();

  return (
    <div className={styles.index}>
      <div className={styles.content}>
        <h1 className={styles.heading}>Jarvis AI Chatbot for Shopify</h1>
        <p className={styles.text}>
          Intelligent AI assistant that provides 24/7 customer support and boosts sales through personalized recommendations.
        </p>
        <div style={{ margin: '20px 0', padding: '15px', backgroundColor: '#fff3cd', border: '1px solid #ffeaa7', borderRadius: '5px' }}>
          <strong>🚨 Important:</strong> This app is designed to work within Shopify Admin. 
          <br />
          <strong>To access your app:</strong>
          <ol style={{ margin: '10px 0', paddingLeft: '20px' }}>
            <li>Go to your Shopify Admin dashboard</li>
            <li>Navigate to "Apps" in the sidebar</li>
            <li>Click on "Jarvis AI Chatbot"</li>
          </ol>
        </div>
        {showForm && (
          <div>
            <p><strong>Or login with your shop domain:</strong></p>
            <Form className={styles.form} method="post" action="/auth/login">
              <label className={styles.label}>
                <span>Shop domain</span>
                <input className={styles.input} type="text" name="shop" />
                <span>e.g: your-store.myshopify.com</span>
              </label>
              <button className={styles.button} type="submit">
                Access Jarvis AI
              </button>
            </Form>
          </div>
        )}
        <ul className={styles.list}>
          <li>
            <strong>24/7 AI Support</strong>. Intelligent chatbot provides instant answers to customer questions around the clock.
          </li>
          <li>
            <strong>Sales Analytics</strong>. Track conversations, customer satisfaction, and revenue generated by your AI assistant.
          </li>
          <li>
            <strong>Easy Customization</strong>. Match your brand with customizable colors, messages, and behavior settings.
          </li>
        </ul>
      </div>
    </div>
  );
}
